In [1]:
from Univariate import Univariate
import pandas as pd

In [2]:
dataset = pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [3]:
quan, qual = Univariate.quanqual(dataset)

In [4]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [5]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [6]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5Rule","Lesser",
                                         "Greater","Min","Max"],columns=quan)

In [7]:
Univariate.Univariate(quan, dataset,descriptive)

          sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean        108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median      108       67       65       66       71       62  265000
Mode          1       62       63       65       60     56.7  300000
Q1:25%     54.5     60.6     60.9       61       60   57.945  240000
Q2:50%      108       67       65       66       71       62  265000
Q3:75%    161.5     75.7       73       72     83.5   66.255  300000
99%      212.86       87    91.86    83.86       97  76.1142     NaN
Q4:100%     215     89.4     97.7       91       98    77.89  940000
IQR         107     15.1     12.1       11     23.5     8.31   60000
1.5Rule   160.5    22.65    18.15     16.5    35.25   12.465   90000
Lesser     -106    37.95    42.75     44.5    24.75    45.48  150000
Greater     322    98.35    91.15     88.5   118.75    78.72  390000
Min           1    40.89       37       50       50    51.21  200000
Max         215     89.4     97.7       91       98    77.89  940000

In [8]:
Lesser, Greater = Univariate.IdentifyOutlier(quan,descriptive)

In [9]:
Lesser

['hsc_p']

In [10]:
Greater

['hsc_p', 'degree_p', 'salary']

In [11]:
 Univariate.ReplaceOutlier(dataset,Lesser,Greater,descriptive)

D:\AI Practice Folder\Data Science\Data Science - Univariate\2.Central Tendency\Univariate.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col][dataset[col]<descriptive[col]['Lesser']]=descriptive[col]['Lesser']
D:\AI Practice Folder\Data Science\Data Science - Univariate\2.Central Tendency\Univariate.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col][dataset[col]>descriptive[col]['Greater']]=descriptive[col]['Greater']

In [12]:
Univariate.Univariate(quan, dataset,descriptive)

          sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean        108  67.3034  66.3347  66.3586  72.1006  62.2782  277649
Median      108       67       65       66       71       62  265000
Mode          1       62       63       65       60     56.7  300000
Q1:25%     54.5     60.6     60.9       61       60   57.945  240000
Q2:50%      108       67       65       66       71       62  265000
Q3:75%    161.5     75.7       73       72     83.5   66.255  300000
99%      212.86       87   91.129    83.86       97  76.1142     NaN
Q4:100%     215     89.4    91.15     88.5       98    77.89  390000
IQR         107     15.1     12.1       11     23.5     8.31   60000
1.5Rule   160.5    22.65    18.15     16.5    35.25   12.465   90000
Lesser     -106    37.95    42.75     44.5    24.75    45.48  150000
Greater     322    98.35    91.15     88.5   118.75    78.72  390000
Min           1    40.89    42.75       50       50    51.21  200000
Max         215     89.4    91.15     88.5       98    77.89  390000

In [13]:
Lesser, Greater = Univariate.IdentifyOutlier(quan,descriptive)

In [14]:
Lesser

[]

In [15]:
Greater

[]

In [17]:
Univariate.freqtable("ssc_p",dataset)

     Unique_Values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            52.00          9            0.087379  0.378641
4            73.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           80.60          1            0.009709  2.048544
99           65.20          1            0.009709  2.058252
100          80.40          1            0.009709  2.067961
101          59.96          1            0.009709  2.077670
102          78.50          1            0.009709  2.087379

[103 rows x 4 columns]